name: Go_Notify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: abinoda/slack-action@v1.0.7
      with:
        args: '{\"channel\":\"C02TAGHRE\",\"text\":\"There is a new push or pull request in the Job Board\"}'
