# fly.toml file generated for devict-job-board on 2022-02-05T11:31:32-06:00

app = "devict-job-board"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

# [build]
#   builder = "paketobuildpacks/builder:base"
#   buildpacks = ["gcr.io/paketo-buildpacks/go"]
#
[env]
  APP_URL = "https://jobs.devict.org"
  APP_ENV = "release"
  FROM_EMAIL = "jobs@mail.devict.org"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  auto_stop_machines = true
  auto_start_machines = true

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
