name: Check
description: Run CI checks
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - run: make build
    - run: make test
